{
    "question": "In Python, exceptions can be considered as:",
    "choices": [
        {
            "choice": "An error in Python syntax",
            "correct": "false"
        },
        {
            "choice": "Objects derived from the base class 'Exception'",
            "correct": "true"
        },
        {
            "choice": "Return statement of a function",
            "correct": "false"
        }
    ]
}